export const words = {
  headerTitle: "Shopping Cart App",
  footerTitle: "© CopyRight Dalia Eltohami @2024",
  content: "Content",
  cartHeader: "Cart Items: ",
  cartItemTitle: "Title: ",
  cartItemQty: "Qty: ",
  cartItemPrice: "Price:",
  cartItemRemoveBtn: "Remove: ",
  cartTotal: "Total Price: ",
  SelectItemsBtn: "Select Products",
  inputName: "Name",
  inputEmail: "Email",
  checkoutBtn: "Checkout",
  orderHeader: "order completed successfully",
  orderInfo: "Order Info",
  orderName: "Name: ",
  orderEmail: "Email: ",
  orderTotal: "Total: ",
  orderItemsHeader: "Selected Items",
  orderProductTitle: "Product: ",
  orderProductQty: "Qty: ",
  orderProductTotal: "Price: ",
  orderTotal2: "Total Price",
  filterHeader: "Number Of Products: ",
  filterSizeTitle: "Size",
  filterOrderTitle: "Order",
  filterBtn: "Filter",
  filterOrderLatest: "Latest",
  filterOrderHighest: "Highest",
  filterOrderLowest: "Lowest",
  addToCartBtn: "Add To Cart",
};
